"""In-house HGSS Safari-Zone encounter resolution (replaces the Pokefinder handoff).

Given the loaded Seed A and the current Safari-Zone block configuration, this computes
*which pokemon* a Sweet-Scent encounter yields at each advance frame -- so Section A.2 can pick
a Metang frame itself instead of round-tripping through Pokefinder (clayton-ctd.8).

How it works (verified against notes/pokefinder_spread.md, 132/132 rows):

  * **Species is one RNG draw.** HGSS Safari uses a special Method-K branch: the encounter slot is
    a flat ``(rand >> 16) % 10`` (10 equally-likely slots), and the species is that slot's entry in
    the area's table.  We never need the PID/level/IV draws to know the species, so no shiny logic.
  * **Frame -> slot:** ``slot(frame) = (advance_rng^(frame+1)(seedA) >> 16) % 10``.  (The encounter
    consumes one advance past the frame you Sweet Scent on; the +1 offset was fit to ground truth.)
  * **Blocks shape the table.** Each area has a default 10-slot table (per time-of-day) plus
    block-conditional entries; each satisfied conditional replaces the next slot from the top, in
    order (PokeFinder ``Encounters4::getHGSSSafari``).  Block scores are the day-multiplier-applied
    values (as Pokefinder takes them), one per type: plains/forest/peak/water.

Data: ``claytonlib/basedata/safari_zones.json`` (all 12 areas, grass/Land only), generated by
``one-offs/extract_safari_zones.py`` from PokeFinder's raw encounter NARC.
"""
import json
from functools import lru_cache
from pathlib import Path

from claytonlib.safari import advance_rng

# Block-type -> index in the score vector.  Index 0 is the game's "no condition" sentinel (a
# conditional's second slot is often (type=0, quantity=0), i.e. always satisfied), so the four real
# categories are 1..4.  Confirmed against ground truth: Metang's Mountain condition is (peak, 56).
BLOCK_TYPES = {"none": 0, "plains": 1, "forest": 2, "peak": 3, "water": 4}
_TOD = {"morning": 0, "day": 1, "night": 2}

_DATA_PATH = Path(__file__).parent / "basedata" / "safari_zones.json"


@lru_cache(maxsize=1)
def _zones() -> dict:
    with open(_DATA_PATH) as f:
        return json.load(f)


@lru_cache(maxsize=1)
def _areas_by_lower() -> dict:
    return {k.lower(): k for k in _zones() if not k.startswith("_")}


def safari_areas() -> list[str]:
    """The Safari-Zone area names that have encounter data (canonical spelling)."""
    return [k for k in _zones() if not k.startswith("_")]


def _area_key(area: str) -> str:
    key = _areas_by_lower().get(str(area).lower())
    if key is None:
        raise ValueError(f"unknown safari area {area!r}; known: {safari_areas()}")
    return key


def _tod_name(tod) -> str:
    if isinstance(tod, int):
        for name, idx in _TOD.items():
            if idx == tod:
                return name
        raise ValueError(f"time-of-day index out of range: {tod}")
    key = str(tod).lower()
    if key not in _TOD:
        raise ValueError(f"unknown time-of-day {tod!r}; use one of {list(_TOD)}")
    return key


def _block_vector(blocks) -> list[int]:
    """Normalize a block-score input to the 5-slot vector indexed by BLOCK_TYPES.

    Accepts a mapping keyed by 'plains'/'forest'/'peak'/'water' (case-insensitive; missing = 0),
    or an already-indexed sequence of length 5 (index 0 = sentinel).
    """
    if isinstance(blocks, dict):
        vec = [0, 0, 0, 0, 0]
        for k, v in blocks.items():
            idx = BLOCK_TYPES.get(str(k).lower())
            if idx is None:
                raise ValueError(f"unknown block type {k!r}; use {list(BLOCK_TYPES)[1:]}")
            vec[idx] = int(v)
        return vec
    vec = list(blocks)
    if len(vec) != 5:
        raise ValueError("indexed block vector must have length 5 (index 0 is the sentinel)")
    return [int(x) for x in vec]


def resolve_safari_slots(area: str, tod, blocks, method: str = "grass") -> list[tuple[str, int]]:
    """The 10 encounter slots (``(species, level)``) for an area/time-of-day/block config.

    ``blocks`` is the day-multiplier-applied score per type (see module docstring).  Mirrors
    PokeFinder ``getHGSSSafari``: each satisfied block-conditional replaces the next slot from the
    top, in conditional order; unsatisfied conditionals are skipped permanently.
    """
    if method != "grass":
        raise NotImplementedError("only grass (Land) encounters are supported")
    grass = _zones()[_area_key(area)]["grass"]
    tod_name = _tod_name(tod)
    normal = grass["normal"][tod_name]
    block = grass["block"][tod_name]
    conds = grass["conditions"]
    vec = _block_vector(blocks)

    out = []
    bi = 0
    for j in range(10):
        specie, level = normal[j]
        while bi < 10:
            t1, q1, t2, q2 = conds[bi]
            if vec[t1] >= q1 and vec[t2] >= q2:
                specie, level = block[bi]
                bi += 1
                break
            bi += 1
        out.append((specie, level))
    return out


def frame_slot(seed: int, frame: int) -> int:
    """The encounter slot (0..9) for Sweet-Scenting on advance ``frame`` of ``seed``."""
    state = seed
    for _ in range(frame + 1):        # +1: the encounter draw is one advance past the frame
        state = advance_rng(state)
    return (state >> 16) % 10


def advance_frame_species(seed: int, frame: int, area: str, tod, blocks) -> tuple[str, int]:
    """The ``(species, level)`` encountered when Sweet-Scenting on ``frame`` of ``seed``."""
    return resolve_safari_slots(area, tod, blocks)[frame_slot(seed, frame)]


def iter_encounter_frames(seed: int, area: str, tod, blocks, target: str = "metang",
                          min_frame: int = 0, max_frame: int = 300):
    """Yield ``(frame, level)`` for every advance frame in ``[min_frame, max_frame]`` whose
    encounter is ``target`` (ascending).  Empty if the target occupies no slot in this config.

    Lets a caller walk successive candidate frames -- e.g. to skip one whose Elm-call approach
    margin is ambiguous and take the next.
    """
    slots = resolve_safari_slots(area, tod, blocks)
    target = str(target).lower()
    hit_slots = {i for i, (sp, _lv) in enumerate(slots) if sp == target}
    if not hit_slots:
        return
    # Walk the RNG forward once rather than re-advancing from the seed for every frame.
    state = seed
    for _ in range(min_frame):
        state = advance_rng(state)
    for frame in range(min_frame, max_frame + 1):
        state = advance_rng(state)                # state is now advance_rng^(frame+1)(seed)
        slot = (state >> 16) % 10
        if slot in hit_slots:
            yield frame, slots[slot][1]


def find_encounter_frame(seed: int, area: str, tod, blocks, target: str = "metang",
                         min_frame: int = 0, max_frame: int = 300) -> tuple[int, int] | None:
    """Nearest advance frame in ``[min_frame, max_frame]`` whose encounter is ``target``.

    Returns ``(frame, level)`` or ``None`` if the target does not occupy any slot in this config
    (e.g. its block requirement is not met) or none is found in range.  Species match is by
    lower-cased name.
    """
    return next(iter_encounter_frames(seed, area, tod, blocks, target, min_frame, max_frame), None)
